using System.Xml;

namespace SW2URDF.MJCF
{
    // Top-level <mujoco model="..."> document. Owns the compiler/asset declarations
    // and the worldbody hierarchy. Writing the model is straightforward XML emission;
    // the heavy lifting (translating a SW2URDF Link tree into the MJCF tree) lives in
    // MJCFBuilder.
    internal class MJCFModel
    {
        public string Name { get; set; }
        public MJCFCompiler Compiler { get; set; }
        public Asset Asset { get; set; }

        // The root body. Conventionally added directly under <worldbody>. Its
        // SuppressTransform should be true so its origin coincides with the world.
        public Body RootBody { get; set; }

        // Whether to emit the standard visual/collision <default> classes. These give
        // visual geoms group=2 with no contact, and collision geoms group=3.
        public bool EmitDefaults { get; set; } = true;

        public MJCFModel(string name)
        {
            Name = name;
            Compiler = new MJCFCompiler();
            Asset = new Asset();
            RootBody = new Body { Name = name, SuppressTransform = true };
        }

        public void WriteMJCF(XmlWriter writer)
        {
            writer.WriteStartDocument();
            writer.WriteComment(" This MJCF was automatically generated by SolidWorks-to-URDF/MJCF Exporter. " +
                "Visual geoms render only; collision geoms participate in physics. ");

            writer.WriteStartElement("mujoco");
            writer.WriteAttributeString("model", Name);

            if (Compiler != null)
            {
                Compiler.WriteMJCF(writer);
            }
            if (EmitDefaults)
            {
                WriteDefaults(writer);
            }
            if (Asset != null)
            {
                Asset.WriteMJCF(writer);
            }

            writer.WriteStartElement("worldbody");
            if (RootBody != null)
            {
                RootBody.WriteMJCF(writer);
            }
            writer.WriteEndElement();

            writer.WriteEndElement();
            writer.WriteEndDocument();
        }

        private static void WriteDefaults(XmlWriter writer)
        {
            // Visual class: rendered, no contact (contype=0, conaffinity=0), group 2.
            // Collision class: not rendered (group 3), has contact, default rgba light.
            writer.WriteStartElement("default");

            writer.WriteStartElement("default");
            writer.WriteAttributeString("class", "visual");
            writer.WriteStartElement("geom");
            writer.WriteAttributeString("contype", "0");
            writer.WriteAttributeString("conaffinity", "0");
            writer.WriteAttributeString("group", "2");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteStartElement("default");
            writer.WriteAttributeString("class", "collision");
            writer.WriteStartElement("geom");
            writer.WriteAttributeString("group", "3");
            writer.WriteAttributeString("rgba", "0.5 0.6 0.7 0.4");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteEndElement();
        }
    }
}
