; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SOLIDWORKS Robot Description Exporter"
#define MyAppVersion "0.5.0"
#define MyAppPublisher "Ethan J. Musser"
#define MyAppURL "https://github.com/ethanmusser/solidworks_robot_description_exporter"

#define MainBinaryName  "SW2RD.dll"
#define SetupBaseName   "sw2rdSetup_"
; BuildConfig defaults to Debug for local iscc runs; CI passes
; /DBuildConfig=Release on the ISCC command line.
#ifndef BuildConfig
  #define BuildConfig "Debug"
#endif
#define DllLocation     AddBackslash(SourcePath + "..\SW2RD\bin\x64\" + BuildConfig) + MainBinaryName
#define BuildVersion    GetVersionNumbersString(DllLocation)
#define CommitVersion   GetFileProductVersion(DllLocation)
#define AVF1            Copy(BuildVersion, 1, Pos(".", BuildVersion) - 1) + "_" + Copy(BuildVersion, Pos(".", BuildVersion) + 1)
#define AVF2            Copy(AVF1,       1, Pos(".", AVF1      ) - 1) + "_" + Copy(AVF1      , Pos(".", AVF1      ) + 1)
#define AppVersionFile  Copy(AVF2,       1, Pos(".", AVF2      ) - 1) + "_" + Copy(AVF2      , Pos(".", AVF2      ) + 1)

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7A712F5D-0AAC-48B1-BE8F-D99238C5D9D6}
AppName={#MyAppName}
AppVersion={#CommitVersion}
VersionInfoVersion={#BuildVersion}
VersionInfoCopyright=2026
VersionInfoProductName={#MyAppName}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=yes
; Default the installer filename to sw2rdSetup_<dll-version>.exe for local
; iscc runs. CI passes /DOutputBaseFilename=sw2rdSetup_<release-tag> so each
; release produces a uniquely named asset.
#ifndef OutputBaseFilename
  #define OutputBaseFilename SetupBaseName + AppVersionFile
#endif
OutputBaseFilename={#OutputBaseFilename}
Compression=lzma                                                        
DefaultDirName="C:\Program Files\SolidWorks Corp\SolidWorks\RobotDescriptionExporter"
SolidCompression=no
PrivilegesRequired=admin
OutputDir=..\..\INSTALL\OUTPUT
SourceDir=..\SW2RD\bin\
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: x64\{#BuildConfig}\*;  DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs; Check: IsWin64;
;Source: x86\Debug\*;  DestDir: {app}; Flags: regserver ignoreversion recursesubdirs createallsubdirs; Check: not IsWin64

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKLM64; Subkey: "SOFTWARE\SolidWorks\Addins\CEC5AFBA-0180-4958-9C47-15F14E2BE922";        ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64
Root: HKCU64; Subkey: "Software\SolidWorks\AddInsStartup\CEC5AFBA-0180-4958-9C47-15F14E2BE922"; ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64

[Code]
{
  COM (un)registration runs from [Code] so we can validate that RegAsm.exe
  exists before launching it, and surface explicit error messages when RegAsm
  fails (missing .NET Framework, registry write blocked by AV, non-zero exit).

  RegAsm.exe lives in the canonical .NET Framework 4.x 64-bit directory; the
  v4.0.30319 folder name has been stable across every 4.x minor version.
}

function RegAsmPath: String;
begin
  Result := ExpandConstant('{win}\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe');
end;

function InstalledDllPath: String;
begin
  Result := ExpandConstant('{app}\SW2RD.dll');
end;

function UninstalledDllPath: String;
begin
  Result := ExpandConstant('{app}\SW2RD.dll');
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  RegAsm, Dll: String;
begin
  if CurStep <> ssPostInstall then
    Exit;
  RegAsm := RegAsmPath;
  Dll := InstalledDllPath;
  if not FileExists(RegAsm) then begin
    MsgBox('Could not register the Robot Description Exporter add-in for SOLIDWORKS:'#13#10 +
           'RegAsm.exe was not found at:'#13#10#13#10 + RegAsm + #13#10#13#10 +
           '.NET Framework 4.x must be installed for the add-in to work.',
           mbCriticalError, MB_OK);
    Exit;
  end;
  WizardForm.StatusLabel.Caption := 'Registering controls ...';
  if not Exec(RegAsm, '"' + Dll + '" /codebase', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then begin
    MsgBox('Failed to launch RegAsm.exe to register the add-in:'#13#10 +
           SysErrorMessage(ResultCode),
           mbError, MB_OK);
  end else if ResultCode <> 0 then begin
    MsgBox('RegAsm.exe exited with code ' + IntToStr(ResultCode) + ' while registering the add-in.'#13#10 +
           'The SOLIDWORKS add-in may not load correctly until this is resolved.',
           mbError, MB_OK);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
  RegAsm, Dll: String;
begin
  if CurUninstallStep <> usUninstall then
    Exit;
  RegAsm := RegAsmPath;
  Dll := UninstalledDllPath;
  if not FileExists(RegAsm) then
    Exit;
  if not FileExists(Dll) then
    Exit;
  Exec(RegAsm, '"' + Dll + '" /unregister', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;
