using System.Collections.Generic;
using System.Xml;

namespace SW2RD.MJCF
{
    // Top-level <mujoco model="..."> document. Owns the compiler/asset declarations
    // and the worldbody hierarchy. Writing the model is straightforward XML emission;
    // the heavy lifting (translating the KinematicTree into the MJCF tree)
    // lives in MJCFBuilder.
    //
    // The worldbody contains:
    //   * world-direct <geom>s (e.g. ground planes), siblings of the bodies
    //   * world-direct <site>s (scene fiducials), also siblings
    //   * one or more top-level <body>s (each an independent kinematic tree)
    //
    // For backwards compatibility with the original single-tree caller, the
    // legacy <see cref="RootBody"/> setter pushes the body into TopLevelBodies
    // (replacing any prior contents) so existing call sites keep working.
    internal class MJCFModel
    {
        public string Name { get; set; }
        public MJCFCompiler Compiler { get; set; }
        public Asset Asset { get; set; }

        public List<Body> TopLevelBodies { get; }
        public List<Geom> WorldGeoms { get; }
        public List<Site> WorldSites { get; }

        /// <summary>
        /// Legacy single-root accessor. Reads / writes the first entry of
        /// <see cref="TopLevelBodies"/>; setting it replaces the entire
        /// list with a one-element list so existing callers continue to
        /// behave exactly as before. New multi-tree callers should append
        /// to <see cref="TopLevelBodies"/> directly.
        /// </summary>
        public Body RootBody
        {
            get => TopLevelBodies.Count > 0 ? TopLevelBodies[0] : null;
            set
            {
                TopLevelBodies.Clear();
                if (value != null)
                {
                    TopLevelBodies.Add(value);
                }
            }
        }

        // Whether to emit the standard visual/collision <default> classes. These give
        // visual geoms group=2 with no contact, and collision geoms group=3.
        public bool EmitDefaults { get; set; } = true;

        public MJCFModel(string name)
        {
            Name = name;
            Compiler = new MJCFCompiler();
            Asset = new Asset();
            TopLevelBodies = new List<Body>
            {
                new Body { Name = name, SuppressTransform = true },
            };
            WorldGeoms = new List<Geom>();
            WorldSites = new List<Site>();
        }

        public void WriteMJCF(XmlWriter writer)
        {
            writer.WriteStartDocument();
            writer.WriteComment(" This MJCF was automatically generated by the SolidWorks Robot Description Exporter (SW2RD). " +
                "Visual geoms render only; collision geoms participate in physics. " +
                "https://github.com/ethanmusser/solidworks_robot_description_exporter ");

            writer.WriteStartElement("mujoco");
            writer.WriteAttributeString("model", Name);

            if (Compiler != null)
            {
                Compiler.WriteMJCF(writer);
            }
            if (EmitDefaults)
            {
                WriteDefaults(writer);
            }
            if (Asset != null)
            {
                Asset.WriteMJCF(writer);
            }

            writer.WriteStartElement("worldbody");
            // World-direct <geom>s and <site>s are emitted as siblings of
            // the top-level bodies. Order: <geom> first, then <site>, then
            // <body>s (matching MJCF reference examples).
            if (WorldGeoms != null)
            {
                foreach (Geom geom in WorldGeoms)
                {
                    geom.WriteMJCF(writer);
                }
            }
            if (WorldSites != null)
            {
                foreach (Site site in WorldSites)
                {
                    site.WriteMJCF(writer);
                }
            }
            if (TopLevelBodies != null)
            {
                foreach (Body body in TopLevelBodies)
                {
                    if (body != null)
                    {
                        body.WriteMJCF(writer);
                    }
                }
            }
            writer.WriteEndElement();

            writer.WriteEndElement();
            writer.WriteEndDocument();
        }

        private static void WriteDefaults(XmlWriter writer)
        {
            // Visual class: rendered, no contact (contype=0, conaffinity=0), group 2.
            // Collision class: not rendered (group 3), has contact, default rgba light.
            writer.WriteStartElement("default");

            writer.WriteStartElement("default");
            writer.WriteAttributeString("class", "visual");
            writer.WriteStartElement("geom");
            writer.WriteAttributeString("contype", "0");
            writer.WriteAttributeString("conaffinity", "0");
            writer.WriteAttributeString("group", "2");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteStartElement("default");
            writer.WriteAttributeString("class", "collision");
            writer.WriteStartElement("geom");
            writer.WriteAttributeString("group", "3");
            writer.WriteAttributeString("rgba", "0.5 0.6 0.7 0.4");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteEndElement();
        }
    }
}
